// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjbwicrfdgywnvzpmfla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qYndpY3JmZGd5d252enBtZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjU1NTUsImV4cCI6MjA2MzY0MTU1NX0.c4lfsyk3PZtRoc0nKIpkGU1GVYSPtXiznIYD_giQQjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);